name: CI Windows Mingw

on:
  push:
    branches: [master, GD-*]
  pull_request:
    branches: [master, GD-*]

  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RELWITHDEBINFO

jobs:


  win-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: 'â¬›', sys: MINGW32 }
          - { icon: 'ðŸŸ¦', sys: MINGW64 }
          - { icon: 'ðŸŸ¨', sys: UCRT64 } # Experimental!
          - { icon: 'ðŸŸ§', sys: CLANG64 } # Experimental!
    name: ðŸš§${{ matrix.icon }}-${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: 'âš™ï¸ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: 'ðŸ§° Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >
          git
          base-devel
          tree
        pacboy: >
          toolchain:p
          libpng:p
          libjpeg-turbo:p
          freetype:p
          libtiff:p
          libwebp:p
          libheif:p
          libraqm:p
          libavif:p
          xpm-nox:p
          cmake:p
          ninja:p

    - name: 'ðŸš§ Cmake Configure'
      run:  |
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_PNG=1 -DENABLE_FREETYPE=1 -DENABLE_XPM=1 -DENABLE_JPEG=1 -DENABLE_WEBP=1 -DENABLE_TIFF=1 -DENABLE_GD_FORMATS=1 -DENABLE_HEIF=1 -DENABLE_RAQM=1 -DENABLE_ICONV=1 -DENABLE_CPP=1 -DBUILD_TEST=1 -B.

    - name: Build
      run: cmake --build .

    - name: Run tests
      working-directory: ${{github.workspace}}
      run: |
        mkdir tmp
        export TMP="$PWD/tmp"
        export CTEST_OUTPUT_ON_FAILURE=1
        ctest
